apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260601-234614-s5q2b6ypm6up-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260601-234614-s5q2b6ypm6up.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260601-234614-s5q2b6ypm6up-service
            port:
              number: 80
